document_root: www
docker_compose:
  overrides:

hooks:
  build: |
    drush dl drupal-7.38
    mv drupal-7.38 www

    cd www/profiles
    git clone git@github.com:proudcity/proud.git
    cd proud
    drush verify-makefile drupal-org.make
    drush make --no-cache --drupal-org drupal-org.make .

    cd ../../sites/all/modules
    mkdir apps
    cd apps
    git clone git@github.com:proudcity/proud_faq.git
    git clone git@github.com:proudcity/proud_event.git
    git clone git@github.com:proudcity/proud_landingpage.git
    git clone git@github.com:proudcity/proud_news.git
    git clone git@github.com:proudcity/proud_webform.git
    git clone git@github.com:proudcity/proud_people.git
    git clone git@github.com:proudcity/proud_agency.git
    git clone git@github.com:proudcity/proud_document.git
    git clone git@github.com:proudcity/proud_social.git
    git clone git@github.com:proudcity/proud_search.git
    mkdir ../dev
    cd ../dev
    git clone --branch 7.x-1.x http://git.drupal.org/project/angular_media.git
    git clone --branch 7.x-1.x http://git.drupal.org/project/media_formatters.git
    git clone --branch 7.x-1.x http://git.drupal.org/project/ckeditor_widgets.git
    mkdir ../../themes/dev
    cd ../../themes/dev
    git clone --branch 7.x-1.x http://git.drupal.org/project/minimalist_admin.git

    drush site-install 
    drush {{alias}} site-install proud --db-url=mysql://drupal:drupal@database/drupal -y

  enable_first: |
